name: n8n-twentycrm-integration

services:
  server:
    image: twentycrm/twenty:v2.9.0@sha256:0afdba1494ea50bad6eb278a20ae35933317483f23501157c2ed866b74d4bc4a
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    ports:
      - '127.0.0.1:${TWENTY_PORT:-3020}:3000'
    environment: &twenty-environment
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:?required}:${PG_DATABASE_PASSWORD:?required}@db:5432/default
      SERVER_URL: http://localhost:${TWENTY_PORT:-3020}
      REDIS_URL: redis://redis:6379
      STORAGE_TYPE: local
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:?required}
      APP_SECRET: ${APP_SECRET:?required}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:3000/healthz']
      interval: 5s
      timeout: 5s
      retries: 30

  worker:
    image: twentycrm/twenty:v2.9.0@sha256:0afdba1494ea50bad6eb278a20ae35933317483f23501157c2ed866b74d4bc4a
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command: ['yarn', 'worker:prod']
    environment:
      <<: *twenty-environment
      DISABLE_DB_MIGRATIONS: 'true'
      DISABLE_CRON_JOBS_REGISTRATION: 'true'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      server:
        condition: service_healthy

  db:
    image: postgres:16.10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD:?required}
      POSTGRES_USER: ${PG_DATABASE_USER:?required}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -h localhost -d postgres']
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7.4.6-alpine
    command: ['redis-server', '--maxmemory-policy', 'noeviction']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db-data:
  server-local-data:
